server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${POSTGRESURL:jdbc:postgresql://localhost:5432/app_db?prepareThreshold=0}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRESUSER:app_user}
    password: ${POSTGRESPASSWORD:app_password}
  
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    timeout: 10000
    lettuce:
      pool:
        max-active: 4
        max-idle: 4
        min-idle: 0
        timeout: 2000ms
    connect-timeout: 2000ms

app:
  brevo:
    apikey: <your-api-key>
    url: https://api.brevo.com
  cloudinary:
    cloud-name: <your-cloud-name>
    api-key: <your-api-key>
    api-secret: <your-api-secret>
  jwt:
    secretKey: <your-secret-key>
    access-duration: 3600 # in seconds
    refreshable-duration: 36000
  folder:
    avatar: "avatar_folder"
    chapter: "chapter_folder"
    story: "story_folder"
    avatar-frame: "avatar_frame_folder"
  admin-email: <your-admin-email>
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
