apiVersion: v1
kind: Secret
metadata:
  name: reading-comic-api-secret
  namespace: reading-comic
type: Opaque
stringData:
  BREVO_API_KEY: "your key"
  AWS_S3_BUCKET_NAME: "your cloud name"
  AWS_REGION: "your region"
  AWS_ACCESS_KEY_ID: "your access key"
  AWS_SECRET_ACCESS_KEY: "your secret key"
  JWT_SECRET_KEY: "your jwt secret key"
  FRONTEND_URL: "http://localhost:3000"
  PORT: "8080"