apiVersion: v1
kind: Secret
metadata:
  name: reading-comic-db-secret
  namespace: reading-comic
type: Opaque
stringData:
  POSTGRES_HOST: "<your-service-name>.<namespace>.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "your_database_name"
  POSTGRES_USER: "your_username"
  POSTGRES_PASSWORD: "your_password"
  REDIS_HOST: "<your-service-name>.<namespace>.svc.cluster.local"
  REDIS_PORT: "6379"